---
- name: update packages
  apt: update_cache=yes

- name: install packages
  apt: name={{item}}
  with_items: packages

- name: add the gitlab server
  shell: "curl {{gitlab_server}} | sudo bash"

- name: install gitlab
  apt: name=gitlab-ce update_cache=yes state=latest

- name: replace gitlab.rb
  template: src='gitlab.rb' dest={{gitlab_dir}}
  notify:
    - gitlab-ctl reconfigure
    - gitlab-ctl restart
  sudo: yes
